Repository FE14-Part4-Team5/reser-on-do, pull requests merged in 2025-06, with the labels that each got.

#14 [feature/modal] - modal 구현
  src/App.tsx
  src/assets/icons/modalwarning.svg
  src/components/modal/modal.module.css
  src/components/modal/modal.tsx
Labels: ✨ 기능 추가 (Feature)

#19 [feature/card] MainCard, MyExperienceCard, ReservationCard 구현
  src/components/ main-card/MainCard.module.css
  src/components/ main-card/MainCard.tsx
  src/components/my-experience-card/MyExperienceCard.module.css
  src/components/my-experience-card/MyExperienceCard.tsx
  src/components/reservation-card/ReservationCard.module.css
  src/components/reservation-card/ReservationCard.tsx
  src/components/state-badge/StateBadge.module.css
  src/components/state-badge/StateBadge.tsx
Labels: ✨ 기능 추가 (Feature)

#21 [chore] 폴더 앞 공백 제거
  src/components/main-card/MainCard.module.css
  src/components/main-card/MainCard.tsx
Labels: 🐞 버그 수정 (Bug)

#20 [feature/gnb-footer] - gnb UI, footer, Mainlayout 구현
  src/App.tsx
  src/components/layout/footer/Footer.module.css
  src/components/layout/footer/Footer.tsx
  src/components/layout/gnb/Header.module.css
  src/components/layout/gnb/Header.tsx
  src/components/layout/main-layout/MainLayout.module.css
  src/components/layout/main-layout/MainLayout.tsx
  src/main.tsx
  src/router.tsx
  src/styles/reset.css
Labels: ✨ 기능 추가 (Feature)

#26 [refactor] SideNavigation 전체적인 코드 리팩토링
  src/App.tsx
  src/assets/icons/icon_calendar.svg
  src/assets/icons/icon_edit.svg
  src/assets/icons/icon_list.svg
  src/assets/icons/icon_setting.svg
  src/assets/icons/icon_user.svg
  src/components/ProfileImage/ProfileImage.tsx
  src/components/ProfileImage/profileImage.css
  src/components/SideNavigation/SideNavigation.tsx
  src/components/SideNavigation/sideNavigation.css
  src/components/side-navigation/SideNavigation.module.css
  src/components/side-navigation/SideNavigation.tsx
  src/components/side-navigation/parts/ProfileImageUploader.module.css
  src/components/side-navigation/parts/ProfileImageUploader.tsx
  src/components/side-navigation/parts/SideNavItem.module.css
  src/components/side-navigation/parts/SideNavItem.tsx
Labels: 🔧 리팩토링 (Refactor)

#25 [feature/common/reservation] - Reservation 구현
  src/components/calendar/CalendarSection.module.css
  src/components/calendar/CalendarSection.tsx
  src/components/reservation/Reservation.module.css
  src/components/reservation/Reservation.tsx
  src/components/reservation/ReservationFooter.module.css
  src/components/reservation/ReservationFooter.tsx
  src/hooks/useViewPortSize.ts
  src/types/calendar.ts
  src/types/reservation.ts
  src/utils/datetime.ts
Labels: ✨ 기능 추가 (Feature)

#38 [feature/page/my-experiences] fallbackImage / 컴포넌트 분리 / 공통으로 쓰일 수 있는 부분 추출
  src/assets/images/error-image.png
  src/assets/images/img_empty.png
  src/components/empty-state/EmptyState.module.css
  src/components/empty-state/EmptyState.tsx
  src/components/main-card/MainCard.tsx
  src/components/my-experience-card/MyExperienceCard.tsx
  src/components/my-experiences-header/MyExperiencesHeader.module.css
  src/components/my-experiences-header/MyExperiencesHeader.tsx
  src/components/reservation-card/ReservationCard.tsx
  src/pages/my-experiences/MyExperiencesPage.module.css
  src/pages/my-experiences/MyExperiencesPage.tsx
  src/pages/my-experiences/components/my-experiences-button/MyExperiencesButton.module.css
  src/pages/my-experiences/components/my-experiences-button/MyExperiencesButton.tsx
  src/pages/my-experiences/components/my-experiences-card-list/MyExperiencesCardList.module.css
  src/pages/my-experiences/components/my-experiences-card-list/MyExperiencesCardList.tsx
Labels: ✨ 기능 추가 (Feature)

#33 [feature/Page/reservation list] Myreservation 구현
  ReservationList.module.css
  src/components/modal/modal.module.css
  src/components/modal/modal.tsx
  src/components/reservation-card/ReservationCard.module.css
  src/components/side-navigation/SideNavigation.module.css
  src/pages/reservation-list/ReservationListPage.module.css
  src/pages/reservation-list/ReservationListPage.tsx
  src/router.tsx
Labels: ✨ 기능 추가 (Feature)

#42 [feature/page/my-experiences] 버튼, 무한스크롤 기능 구현
  ReservationList.module.css
  package-lock.json
  package.json
  src/components/side-navigation/SideNavigation.module.css
  src/hooks/useInfiniteMyActivities.ts
  src/hooks/useMyActivities.ts
  src/pages/add-experiences/AddExperiences.module.css
  src/pages/add-experiences/AddExperiences.tsx
  src/pages/edit-experiences/EditExperiences.module.css
  src/pages/edit-experiences/EditExperiences.tsx
  src/pages/my-experiences/MyExperiencesPage.tsx
  src/pages/my-experiences/components/my-experiences-button/MyExperiencesButton.module.css
  src/pages/my-experiences/components/my-experiences-button/MyExperiencesButton.tsx
  src/pages/my-experiences/components/my-experiences-card-list/MyExperiencesCardList.module.css
  src/pages/my-experiences/components/my-experiences-card-list/MyExperiencesCardList.tsx
  src/pages/my-experiences/example/Modal.module.css
  src/pages/my-experiences/example/Modal.tsx
  src/pages/my-experiences/example/example.ts
  src/pages/reservation-status/ReservationStatus.module.css
  src/pages/reservation-status/ReservationStatus.tsx
  src/router.tsx
Labels: ✨ 기능 추가 (Feature)

#40 [feature/my-profile-ui] - my-profile 페이지 UI, 반응형 구현 및 유효성 검사 적용
  package-lock.json
  package.json
  src/components/layout/footer/Footer.module.css
  src/components/layout/gnb/Header.module.css
  src/components/layout/gnb/Header.tsx
  src/components/reservation/Reservation.tsx
  src/components/reservation/ReservationFooter.tsx
  src/components/side-navigation/SideNavigation.tsx
  src/components/side-navigation/parts/SideNavItem.tsx
  src/hooks/useMyProfileUpdateForm.ts
  src/pages/my-profile/MyProfilePage.module.css
  src/pages/my-profile/MyProfilePage.tsx
  src/pages/my-profile/components/ProfileForm.module.css
  src/pages/my-profile/components/ProfileForm.tsx
  src/router.tsx
Labels: 🐞 버그 수정 (Bug), ✨ 기능 추가 (Feature)

#44 [feature/page/detail] DetailPage 구현 및 테스트
  package-lock.json
  package.json
  src/assets/icons/icon_star.svg
  src/components/reservation/Reservation.module.css
  src/components/reservation/Reservation.tsx
  src/hooks/useExperience.ts
  src/pages/detail/DetailPage.module.css
  src/pages/detail/DetailPage.tsx
  src/pages/detail/components/ReviewCard.module.css
  src/pages/detail/components/ReviewCard.tsx
  src/pages/detail/example/example.ts
  src/router.tsx
Labels: ✨ 기능 추가 (Feature)

#43 [feature/page/reservation-list] reservation card 제작
  src/components/reservation-card/ReservationCard.module.css
  src/pages/reservation-list/ReservationListPage.module.css
  src/pages/reservation-list/ReservationListPage.tsx
  src/router.tsx
Labels: 🐞 버그 수정 (Bug), ✨ 기능 추가 (Feature)

#45 [feature/api] API 함수 추가 및 type 정의
  package-lock.json
  package.json
  src/apis/activities.ts
  src/apis/auth.ts
  src/apis/myActivities.ts
  src/apis/myNotifications.ts
  src/apis/myReservations.ts
  src/apis/oauth.ts
  src/apis/users.ts
  src/types/api/activitiesType.ts
  src/types/api/authType.ts
  src/types/api/errorMessageType.ts
  src/types/api/myActivitiesType.ts
  src/types/api/myNotificationsType.ts
  src/types/api/myReservationsType.ts
  src/types/api/oauthType.ts
  src/types/api/usersType.ts
Labels: ✨ 기능 추가 (Feature)

#48 [Feature/my-profile-api] my-profile 페이지 api 관련 기능 구현 및 테스트
  package-lock.json
  src/apis/users.ts
  src/components/layout/gnb/Header.tsx
  src/hooks/useFormChangeChecker.ts
  src/hooks/useMyProfile.ts
  src/pages/my-profile/MyProfilePage.tsx
  src/pages/my-profile/components/ProfileForm.tsx
  src/router.tsx
Labels: ✨ 기능 추가 (Feature)

#54 [feature/page/my-experiences] suspense 및 error boundary 구현
  package-lock.json
  package.json
  src/App.tsx
  src/assets/images/cry.png
  src/components/main-card/MainCard.module.css
  src/components/reservation-card/ReservationCard.module.css
  src/hooks/useInfiniteMyActivities.ts
  src/pages/my-experiences/MyExperiencesPage.tsx
  src/pages/my-experiences/components/error/ErrorUI.module.css
  src/pages/my-experiences/components/error/ErrorUI.tsx
  src/pages/my-experiences/components/loading/Loading.tsx
  src/pages/my-experiences/components/loading/LoadingUI.module.css
  src/router.tsx
  src/types/api/myActivitiesType.ts
Labels: ✨ 기능 추가 (Feature)

#47 [page/reservation-list] navigationcard 위치이동, router 오류 해결 및 반응형 (진행중)
  src/components/modal/modal.module.css
  src/components/reservation-card/ReservationCard.module.css
  src/pages/reservation-list/ReservationListPage.module.css
  src/pages/reservation-list/ReservationListPage.tsx
  src/router.tsx
Labels: ✨ 기능 추가 (Feature)

#60 [feature/oauth] OAuth 기능 추가
  src/apis/auth.ts
  src/components/Input/Input.module.css
  src/pages/login/LoginPage.tsx
  src/pages/login/components/Login.module.css
  src/pages/oauthkakaocallback/OAuthKakaoCallback.tsx
  src/pages/signup/components/Signup.module.css
  src/stores/useAuthStore.ts
  src/types/api/authType.ts
  src/types/api/sharedType.ts
Labels: ✨ 기능 추가 (Feature)

#67 [feature/main-ui] 메인페이지 ui 구현
  src/assets/images/main_background.svg
  src/components/Search/Search.module.css
  src/components/layout/gnb/Header.module.css
  src/components/layout/gnb/Header.tsx
  src/components/main-card/MainCard.module.css
  src/hooks/useHorizontalScroll.ts
  src/pages/main/MainPage.module.css
  src/pages/main/MainPage.tsx
  src/pages/main/components/banner/Banner.module.css
  src/pages/main/components/banner/Banner.tsx
  src/pages/main/components/category/ActivityCategory.module.css
  src/pages/main/components/category/ActivityCategory.tsx
  src/pages/main/components/category/CategoryList.ts
  src/pages/main/components/experience-card-list/ExperienceCardList.module.css
  src/pages/main/components/experience-card-list/ExperiencesCardList.tsx
  src/pages/main/components/horizontal-card-list/HorizontalCardList.module.css
  src/pages/main/components/horizontal-card-list/HorizontalCardList.tsx
  src/pages/main/example/MockCardData.ts
  src/router.tsx
Labels: ✨ 기능 추가 (Feature), 🎨 스타일 (Style)

#63 [Feature/reservation contact] 예약 내역 페이지 API
  src/apis/myReservations.ts
  src/components/modal/modal.tsx
  src/components/side-navigation/SideNavigation.tsx
  src/pages/reservation-list/ReservationListPage.tsx
  src/pages/reservation-list/components/loading/reservationlist.ts
  src/router.tsx
Labels: ✨ 기능 추가 (Feature)

#73 [feature/edit-experiences] 페이지 기능 구현 완료
  src/components/my-experience-card/MyExperienceCard.module.css
  src/components/reservation-card/ReservationCard.module.css
  src/components/reservation-card/ReservationCard.tsx
  src/hooks/useDaumPostcode.ts
  src/pages/add-edit-experiences/add-experiences/AddExperiences.module.css
  src/pages/add-edit-experiences/add-experiences/AddExperiences.tsx
  src/pages/add-edit-experiences/components/dropdown/Dropdown.module.css
  src/pages/add-edit-experiences/components/dropdown/Dropdown.tsx
  src/pages/add-edit-experiences/components/general-info-section/GeneralInfoSection.module.css
  src/pages/add-edit-experiences/components/general-info-section/GeneralInfoSection.tsx
  src/pages/add-edit-experiences/components/image-upload-section/ImageUploadSection.module.css
  src/pages/add-edit-experiences/components/image-upload-section/ImageUploadSection.tsx
  src/pages/add-edit-experiences/components/schedule-section/ScheduleSection.module.css
  src/pages/add-edit-experiences/components/schedule-section/ScheduleSection.tsx
  src/pages/add-edit-experiences/edit-experiences/EditExperiences.module.css
  src/pages/add-edit-experiences/edit-experiences/EditExperiences.tsx
  src/pages/add-edit-experiences/schema/schema.ts
  src/pages/add-experiences/components/image-upload-section/ImageUploadSection.tsx
  src/pages/add-experiences/schema/schema.ts
  src/pages/edit-experiences/EditExperiences.module.css
  src/pages/edit-experiences/EditExperiences.tsx
  src/pages/my-experiences/MyExperiencesPage.tsx
  src/pages/my-experiences/components/loading/Loading.tsx
  src/pages/my-experiences/components/my-experiences-button/MyExperiencesButton.tsx
  src/pages/my-experiences/components/my-experiences-card-list/MyExperiencesCardList.tsx
  src/router.tsx
  src/types/api/myActivitiesType.ts
Labels: ✨ 기능 추가 (Feature)

#76 [page/detail-ui] 상세 페이지 이미지 fallback 및 레이아웃 개선
  src/components/calendar/CalendarSection.tsx
  src/hooks/useExperience.ts
  src/pages/detail/DetailPage.module.css
  src/pages/detail/DetailPage.tsx
  src/pages/detail/example/example.ts
Labels: ✨ 기능 추가 (Feature)

#79 [feature/reservation-status] 예약 현황 페이지 UI 및 기능 개발
  src/apis/myActivities.ts
  src/pages/login/LoginPage.tsx
  src/pages/reservation-status/ReservationStatus.module.css
  src/pages/reservation-status/ReservationStatus.tsx
  src/pages/reservation-status/components/Calendar.module.css
  src/pages/reservation-status/components/Calendar.tsx
  src/pages/reservation-status/components/CalendarModal.module.css
  src/pages/reservation-status/components/CalendarModal.tsx
  src/types/api/myActivitiesType.ts
Labels: ✨ 기능 추가 (Feature)

#82 [fix/login] 로그인 관련 수정 사항
  src/apis/activities.ts
  src/apis/axiosInstance.ts
  src/pages/login/LoginPage.tsx
  src/pages/login/components/Login.module.css
  src/pages/login/components/Login.tsx
  src/pages/signup/components/Signup.module.css
  src/pages/signup/components/Signup.tsx
  src/stores/useAuthStore.ts
Labels: 🐞 버그 수정 (Bug)

#83 [fix/login] zustand clear 함수 추가, API 키 변수명 변경
  src/pages/login/LoginPage.tsx
  src/pages/signup/SignupPage.tsx
  src/stores/useAuthStore.ts
Labels: 🐞 버그 수정 (Bug), ✨ 기능 추가 (Feature)

#87 [fix/add, edit, my-experiences] 테스트 수정 사항 반영
  src/components/modal/ConfirmModal.module.css
  src/components/modal/ConfirmModal.tsx
  src/hooks/useBackBlocker.ts
  src/pages/add-edit-experiences/add-experiences/AddExperiences.tsx
  src/pages/add-edit-experiences/components/general-info-section/GeneralInfoSection.tsx
  src/pages/add-edit-experiences/components/image-upload-section/ImageUploadSection.tsx
  src/pages/add-edit-experiences/components/schedule-section/ScheduleSection.tsx
  src/pages/add-edit-experiences/edit-experiences/EditExperiences.tsx
  src/pages/add-edit-experiences/schema/schema.ts
  src/pages/detail/DetailPage.tsx
  src/pages/my-experiences/MyExperiencesPage.tsx
Labels: 🐞 버그 수정 (Bug), ✨ 기능 추가 (Feature)

#88 [fix/detail] 체험 상세 페이지 수정
  src/apis/activities.ts
  src/apis/myActivities.ts
  src/components/reservation/Reservation.module.css
  src/pages/detail/DetailPage.module.css
  src/pages/detail/DetailPage.tsx
Labels: 🐞 버그 수정 (Bug), ✨ 기능 추가 (Feature)

#89 [fix/notification]: 알림 모달 수정
  src/components/modal/NotificationModal.module.css
  src/components/modal/NotificationModal.tsx
Labels: 🐞 버그 수정 (Bug), ✨ 기능 추가 (Feature)

#94 [fix/ErrorUI] fallback ui에서 홈으로 가지지 않는 현상 수정
  src/pages/my-experiences/components/error/ErrorUI.tsx
Labels: 🐞 버그 수정 (Bug)

#97 [fix/reservation-list] 기능 구현 및 버그 수정
  src/apis/myReservations.ts
  src/components/modal/modal.tsx
  src/components/reservation-card/ReservationCard.module.css
  src/pages/add-edit-experiences/add-experiences/AddExperiences.tsx
  src/pages/my-experiences/MyExperiencesPage.module.css
  src/pages/reservation-list/ReservationListPage.module.css
  src/pages/reservation-list/ReservationListPage.tsx
  src/router.tsx
  src/types/api/myReservationsType.ts
Labels: 🐞 버그 수정 (Bug), ✨ 기능 추가 (Feature)

#96 [Fix/my-profile-test] my-profile 페이지 테스트 수정사항 반영
  src/components/layout/gnb/Header.module.css
  src/components/layout/gnb/Header.tsx
  src/components/main-card/MainCard.module.css
  src/components/main-card/MainCard.tsx
  src/hooks/useActivities.ts
  src/pages/main/MainPage.module.css
  src/pages/main/MainPage.tsx
  src/pages/main/components/loading/MainLoadingUI.module.css
  src/pages/main/components/loading/MainLodingUI.tsx
  src/router.tsx
Labels: 🐞 버그 수정 (Bug), 🎨 스타일 (Style)

#98 [fix/reservation-status] 예약 현황 페이지 수정 사항 개발
  src/pages/add-edit-experiences/components/dropdown/Dropdown.tsx
  src/pages/reservation-status/ReservationStatus.module.css
  src/pages/reservation-status/ReservationStatus.tsx
  src/pages/reservation-status/components/Calendar.module.css
  src/pages/reservation-status/components/Calendar.tsx
  src/pages/reservation-status/components/CalendarModal.module.css
  src/pages/reservation-status/components/CalendarModal.tsx
Labels: 🐞 버그 수정 (Bug)

#104 [fix/reservation-status] 예약 현황 페이지 에러 사항 수정 완료
  src/pages/reservation-status/components/Calendar.module.css
  src/pages/reservation-status/components/Calendar.tsx
  src/pages/reservation-status/components/CalendarModal.module.css
  src/pages/reservation-status/components/CalendarModal.tsx
Labels: 🐞 버그 수정 (Bug), ✨ 기능 추가 (Feature), 🎨 스타일 (Style)
